### GET all the segments
GET http://localhost:8080/segments
Accept: application/json

### GET segment by id
GET http://localhost:8080/segments/2
Accept: application/json

### POST a new segment
POST http://localhost:8080/segments
Accept: application/json

{
 "id": "3",
 "title": "hello"
}

###